name: ci-alpine

on:
  push:
    branches:
      - "main"
    paths:
      - '**/ci-alpine.yml'
      - '**/Dockerfile.alpine'
      - '**/entrypoint2.sh'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USER }}/aws-cli-alpine
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          labels: |
            maintainer="Asdrubal Gonzalez Penton"
            org.opencontainers.image.authors="Asdrubal Gonzalez Penton"

      - name: Debug
        run: |
          echo "GitHub workspace: ${{ github.workspace }}"
          ls -la

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ github.workspace }}/Dockerfile.alpine
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # tags: ${{ secrets.DOCKER_USER }}/aws-cli:latest
          platforms: linux/amd64,linux/arm64
